run:
  timeout: 5m

linters:
  enable:
    - govet
    run:
      timeout: 5m

    linters:
      enable:
        - govet
        - staticcheck
        - errcheck
        - gofmt
        - ineffassign

    issues:
      exclude-rules:
        - path: _test.go
          linters:
            - gofmt
